# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_web', '0003_product_productparts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productparts',
            old_name='name',
            new_name='part_name',
        ),
    ]
